CREATE USER boost WITH PASSWORD 'Test1ng';
CREATE DATABASE blog;
GRANT ALL PRIVILEGES ON DATABASE blog TO boost;
COMMIT;
CREATE USER boost_test WITH PASSWORD 'Test1ng_test';
CREATE DATABASE blog_test;
GRANT ALL PRIVILEGES ON DATABASE blog_test TO boost_test;
COMMIT;